service:
  name: reminder-bot
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-dotenv-plugin
  - serverless-dynamodb-local
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x
  region: ap-northeast-1
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

functions:
  schedule_regist:
    handler: src/schedule.regist
    memorySize: 128
    timeout: 900
    events:
      - http:
          method: post
          path: schedule/regist
          cors: true

  schedule_update:
    handler: src/schedule.update
    memorySize: 128
    timeout: 900
    events:
      - http:
          method: post
          path: schedule/update
          cors: true

  schedule_delete:
    handler: src/schedule.remove
    memorySize: 128
    timeout: 900
    events:
      - http:
          method: post
          path: schedule/remove
          cors: true

  notify:
    handler: src/notify.routine
    memorySize: 128
    timeout: 900
    events:
      - schedule:
          rate: rate(1 minutes)
          enabled: true
          input:
            key1: value1
            key2: value2
            stageParams:
              stage: dev